services:
  api_gateway:
      # Build parameters for the container
      build: .
      image: aljovanmp/ticket_be_api_mailer:latest
      container_name: ticket_api_mailer
      ports:
        # Maps ports to be accessed by the app outside of the container
        - "4004:4000"
      environment:
        MIX_ENV: "dev"
        SECRET_KEY_BASE: 
        GMAIL_CLIENT_ID: 
        GMAIL_CLIENT_SECRET: 
        GMAIL_REFRESH_TOKEN: 

      networks:
        - shared_network
      develop:
        watch:
          - action: sync
            path: ./lib
            target: /app/lib
          - action: sync+restart
            path: ./config
            target: /app/config
          - action: sync+restart
            path: ./lib/gateway/grpc_client.ex
            target: /app/lib/gateway/grpc_client.ex
          - action: rebuild
            path: mix.exs

  dummy:
      image: alpine:latest
      init: true
      command: ["sh", "-c", "while true; do sleep 2; done"]

networks:
  shared_network:
    external: true